- hosts: all
  become: yes
  
  tasks:
  - name: Generate /etc/ssh/ RSA host key
    command : ssh-keygen -q -t rsa -f /tmp/ssh_host_rsa_key -C "" -N ""
    args:
      creates: /tmp/ssh_host_rsa_key
