- hosts: all
  become: yes
  tasks:
    - name: Generate an OpenSSH keypair with the default values
      community.crypto.openssh_keypair:
        path: /tmp/id_ssh_rsa
        passphrase: super_secret_password
