- name: generate SSH key
  hosts: all
  vars:
    ansible_user: ansible
    ssh_key_filename: id_rsa_myproject
    ssh_passphrase: changeme

  tasks:

    - name: generate SSH key "{{ssh_key_filename}}"
      user:
        group: admin
        name: "{{ansible_user}}"
        generate_ssh_key: yes
        ssh_key_type: rsa
        ssh_key_bits: 4096
        ssh_key_file: /tmp/{{ssh_key_filename}}
        force: no
