- hosts: all
  become: yes

  tasks:
  
    - name: Generate an OpenSSH keypair with the default valuesa nd encrypted private key
      community.crypto.openssh_keypair:
        path: /tmp/id_ssh_rsa
        passphrase: super_secret_password
      delegate_to: localhost
